### ISSUE TITLE
Import into Laravel: namespace not as in docs

### ISSUE THREAD

**Issue by ipearx** [Runalyze/dem-reader#4]
I imported into laravel, and it took a long time to figure out that the namespace was meant to be:

`Runalyze\DEM\Provider\GeoTIFF\SRTM4Provider`

NOT Runalyze\DEM\Provider\SRTM4Provider as described in the documentation. Hope that helps.

**Comment by laufhannes** [comment]
Thanks for the hint! I've fixed the readme file.
